name:                y2020
version:             0.1.0.0
github:              "mx42/y2020"
license:             BSD3
author:              "Xavier Morel"
maintainer:          "morelx42@gmail.com"
copyright:           "2019 Xavier Morel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mx42/y2020#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers

library:
  source-dirs: src

executables:
  y2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - y2020

tests:
  y2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - y2020
