name:                haskellAoC
version:             0.1.0.0
github:              "mx42/haskellAoC"
license:             BSD3
author:              "Xavier Morel"
maintainer:          "morelx42@gmail.com"
copyright:           "2020 Xavier Morel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mx42/haskellAoC#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- directory
- matrix
- memoize
- pureMD5
- scientific
- sort
- split
- text
- unordered-containers
- utf8-string
- vector

library:
  source-dirs: src

executables:
  haskellAoC-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellAoC

tests:
  haskellAoC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellAoC
